### ISSUE TITLE
Dolfin error

### ISSUE THREAD

**Issue by hasanelm** [wilhelmbraun/1D-Fokker-Planck-equation#1]
When I'm trying to compile your code with spyder in anaconda environment under mac os, I receive the following error

ModuleNotFoundError: No module named 'dolfin'

Please if you can help me to resolve such an issue

best regards

**Comment by wilhelmbraun** [comment]
Hi, you either need to install dolfin or comment out the line (the code does not require dolfin).

Best, Wilhelm

**Comment by ShaneGervais** [comment]
I'm experiencing a similar issue. I commented importing dolphin but still won't run even if I comment all the other error it would give. Tried to find online how to install but am unsure how to. 

Thank you, best regards

**Comment by wilhelmbraun** [comment]
Sorry, the code does require dolfin, so please don't comment it out. I confused it with the other repository (1D_finite_elements), where dolfin is not needed. Here are the installation instructions: https://fenicsproject.org/download/

Note, however, that the code is from 2017 so maybe some functions have changed or have a different syntax.
